name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        cache: 'true'
        go-version: '1.24.1'

    - name: Test
      run: go test -v ./...

  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          cache: 'true'
          go-version: '1.24.1'

      - name: Test
        run: go test -v ./... -bench . -run ^$ -benchtime=100000x
